/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BankAccountVerification
 */
public class BankAccountVerificationTest {
    private final BankAccountVerification model = new BankAccountVerification();

    /**
     * Model tests for BankAccountVerification
     */
    @Test
    public void testBankAccountVerification() {
        // TODO: test BankAccountVerification
    }

    /**
     * Test the property 'bankAccount'
     */
    @Test
    public void bankAccountTest() {
        // TODO: test bankAccount
    }

    /**
     * Test the property 'ifsc'
     */
    @Test
    public void ifscTest() {
        // TODO: test ifsc
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'caseId'
     */
    @Test
    public void caseIdTest() {
        // TODO: test caseId
    }

}
