/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BarCodeShareRequestBody
 */
public class BarCodeShareRequestBodyTest {
    private final BarCodeShareRequestBody model = new BarCodeShareRequestBody();

    /**
     * Model tests for BarCodeShareRequestBody
     */
    @Test
    public void testBarCodeShareRequestBody() {
        // TODO: test BarCodeShareRequestBody
    }

    /**
     * Test the property 'caseId'
     */
    @Test
    public void caseIdTest() {
        // TODO: test caseId
    }

    /**
     * Test the property 'emailIds'
     */
    @Test
    public void emailIdsTest() {
        // TODO: test emailIds
    }

}
