/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BlockRequestBody
 */
public class BlockRequestBodyTest {
    private final BlockRequestBody model = new BlockRequestBody();

    /**
     * Model tests for BlockRequestBody
     */
    @Test
    public void testBlockRequestBody() {
        // TODO: test BlockRequestBody
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'blockRemark'
     */
    @Test
    public void blockRemarkTest() {
        // TODO: test blockRemark
    }

    /**
     * Test the property 'enums'
     */
    @Test
    public void enumsTest() {
        // TODO: test enums
    }

}
