/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CaseDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MCACompanyMasterDataRequest
 */
public class MCACompanyMasterDataRequestTest {
    private final MCACompanyMasterDataRequest model = new MCACompanyMasterDataRequest();

    /**
     * Model tests for MCACompanyMasterDataRequest
     */
    @Test
    public void testMCACompanyMasterDataRequest() {
        // TODO: test MCACompanyMasterDataRequest
    }

    /**
     * Test the property 'consent'
     */
    @Test
    public void consentTest() {
        // TODO: test consent
    }

    /**
     * Test the property 'cin'
     */
    @Test
    public void cinTest() {
        // TODO: test cin
    }

    /**
     * Test the property 'activeCompliance'
     */
    @Test
    public void activeComplianceTest() {
        // TODO: test activeCompliance
    }

    /**
     * Test the property 'clientData'
     */
    @Test
    public void clientDataTest() {
        // TODO: test clientData
    }

}
