/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CaseDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MCASignatoryRequest
 */
public class MCASignatoryRequestTest {
    private final MCASignatoryRequest model = new MCASignatoryRequest();

    /**
     * Model tests for MCASignatoryRequest
     */
    @Test
    public void testMCASignatoryRequest() {
        // TODO: test MCASignatoryRequest
    }

    /**
     * Test the property 'consent'
     */
    @Test
    public void consentTest() {
        // TODO: test consent
    }

    /**
     * Test the property 'cin'
     */
    @Test
    public void cinTest() {
        // TODO: test cin
    }

    /**
     * Test the property 'iec'
     */
    @Test
    public void iecTest() {
        // TODO: test iec
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'clientData'
     */
    @Test
    public void clientDataTest() {
        // TODO: test clientData
    }

}
