/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelAPIResponse
 */
public class ModelAPIResponseTest {
    private final ModelAPIResponse model = new ModelAPIResponse();

    /**
     * Model tests for ModelAPIResponse
     */
    @Test
    public void testModelAPIResponse() {
        // TODO: test ModelAPIResponse
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'requestDateTime'
     */
    @Test
    public void requestDateTimeTest() {
        // TODO: test requestDateTime
    }

    /**
     * Test the property 'httpstatuscode'
     */
    @Test
    public void httpstatuscodeTest() {
        // TODO: test httpstatuscode
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'uniqueRequestId'
     */
    @Test
    public void uniqueRequestIdTest() {
        // TODO: test uniqueRequestId
    }

    /**
     * Test the property 'barcode'
     */
    @Test
    public void barcodeTest() {
        // TODO: test barcode
    }

}
