/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NewCaseRequestBody
 */
public class NewCaseRequestBodyTest {
    private final NewCaseRequestBody model = new NewCaseRequestBody();

    /**
     * Model tests for NewCaseRequestBody
     */
    @Test
    public void testNewCaseRequestBody() {
        // TODO: test NewCaseRequestBody
    }

    /**
     * Test the property 'caseId'
     */
    @Test
    public void caseIdTest() {
        // TODO: test caseId
    }

    /**
     * Test the property 'caseName'
     */
    @Test
    public void caseNameTest() {
        // TODO: test caseName
    }

    /**
     * Test the property 'caseDescription'
     */
    @Test
    public void caseDescriptionTest() {
        // TODO: test caseDescription
    }

    /**
     * Test the property 'companyType'
     */
    @Test
    public void companyTypeTest() {
        // TODO: test companyType
    }

    /**
     * Test the property 'barcode'
     */
    @Test
    public void barcodeTest() {
        // TODO: test barcode
    }

    /**
     * Test the property 'barCodeStatus'
     */
    @Test
    public void barCodeStatusTest() {
        // TODO: test barCodeStatus
    }

}
