/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NewCompanyRegistrationRequest
 */
public class NewCompanyRegistrationRequestTest {
    private final NewCompanyRegistrationRequest model = new NewCompanyRegistrationRequest();

    /**
     * Model tests for NewCompanyRegistrationRequest
     */
    @Test
    public void testNewCompanyRegistrationRequest() {
        // TODO: test NewCompanyRegistrationRequest
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'authSignEmail'
     */
    @Test
    public void authSignEmailTest() {
        // TODO: test authSignEmail
    }

    /**
     * Test the property 'authSignMobile'
     */
    @Test
    public void authSignMobileTest() {
        // TODO: test authSignMobile
    }

    /**
     * Test the property 'panNumber'
     */
    @Test
    public void panNumberTest() {
        // TODO: test panNumber
    }

    /**
     * Test the property 'gstinNumber'
     */
    @Test
    public void gstinNumberTest() {
        // TODO: test gstinNumber
    }

    /**
     * Test the property 'companyType'
     */
    @Test
    public void companyTypeTest() {
        // TODO: test companyType
    }

    /**
     * Test the property 'gstinctb'
     */
    @Test
    public void gstinctbTest() {
        // TODO: test gstinctb
    }

    /**
     * Test the property 'gstinLegalName'
     */
    @Test
    public void gstinLegalNameTest() {
        // TODO: test gstinLegalName
    }

    /**
     * Test the property 'gstinTradeName'
     */
    @Test
    public void gstinTradeNameTest() {
        // TODO: test gstinTradeName
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'memeberId'
     */
    @Test
    public void memeberIdTest() {
        // TODO: test memeberId
    }

}
