/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BankAccountVerification
 */
@JsonPropertyOrder({
  BankAccountVerification.JSON_PROPERTY_BANK_ACCOUNT,
  BankAccountVerification.JSON_PROPERTY_IFSC,
  BankAccountVerification.JSON_PROPERTY_NAME,
  BankAccountVerification.JSON_PROPERTY_PHONE,
  BankAccountVerification.JSON_PROPERTY_CASE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class BankAccountVerification {
  public static final String JSON_PROPERTY_BANK_ACCOUNT = "bank_account";
  private String bankAccount;

  public static final String JSON_PROPERTY_IFSC = "ifsc";
  private String ifsc;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_CASE_ID = "caseId";
  private String caseId;

  public BankAccountVerification() {
  }

  public BankAccountVerification bankAccount(String bankAccount) {
    
    this.bankAccount = bankAccount;
    return this;
  }

   /**
   * Get bankAccount
   * @return bankAccount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BANK_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBankAccount() {
    return bankAccount;
  }


  @JsonProperty(JSON_PROPERTY_BANK_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBankAccount(String bankAccount) {
    this.bankAccount = bankAccount;
  }


  public BankAccountVerification ifsc(String ifsc) {
    
    this.ifsc = ifsc;
    return this;
  }

   /**
   * Get ifsc
   * @return ifsc
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IFSC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIfsc() {
    return ifsc;
  }


  @JsonProperty(JSON_PROPERTY_IFSC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIfsc(String ifsc) {
    this.ifsc = ifsc;
  }


  public BankAccountVerification name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public BankAccountVerification phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public BankAccountVerification caseId(String caseId) {
    
    this.caseId = caseId;
    return this;
  }

   /**
   * Get caseId
   * @return caseId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCaseId() {
    return caseId;
  }


  @JsonProperty(JSON_PROPERTY_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCaseId(String caseId) {
    this.caseId = caseId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountVerification bankAccountVerification = (BankAccountVerification) o;
    return Objects.equals(this.bankAccount, bankAccountVerification.bankAccount) &&
        Objects.equals(this.ifsc, bankAccountVerification.ifsc) &&
        Objects.equals(this.name, bankAccountVerification.name) &&
        Objects.equals(this.phone, bankAccountVerification.phone) &&
        Objects.equals(this.caseId, bankAccountVerification.caseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankAccount, ifsc, name, phone, caseId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountVerification {\n");
    sb.append("    bankAccount: ").append(toIndentedString(bankAccount)).append("\n");
    sb.append("    ifsc: ").append(toIndentedString(ifsc)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    caseId: ").append(toIndentedString(caseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

