/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BarCodeShareRequestBody
 */
@JsonPropertyOrder({
  BarCodeShareRequestBody.JSON_PROPERTY_CASE_ID,
  BarCodeShareRequestBody.JSON_PROPERTY_EMAIL_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class BarCodeShareRequestBody {
  public static final String JSON_PROPERTY_CASE_ID = "caseId";
  private String caseId;

  public static final String JSON_PROPERTY_EMAIL_IDS = "emailIds";
  private List<String> emailIds;

  public BarCodeShareRequestBody() {
  }

  public BarCodeShareRequestBody caseId(String caseId) {
    
    this.caseId = caseId;
    return this;
  }

   /**
   * Get caseId
   * @return caseId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCaseId() {
    return caseId;
  }


  @JsonProperty(JSON_PROPERTY_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCaseId(String caseId) {
    this.caseId = caseId;
  }


  public BarCodeShareRequestBody emailIds(List<String> emailIds) {
    
    this.emailIds = emailIds;
    return this;
  }

  public BarCodeShareRequestBody addEmailIdsItem(String emailIdsItem) {
    if (this.emailIds == null) {
      this.emailIds = new ArrayList<>();
    }
    this.emailIds.add(emailIdsItem);
    return this;
  }

   /**
   * Get emailIds
   * @return emailIds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getEmailIds() {
    return emailIds;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailIds(List<String> emailIds) {
    this.emailIds = emailIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarCodeShareRequestBody barCodeShareRequestBody = (BarCodeShareRequestBody) o;
    return Objects.equals(this.caseId, barCodeShareRequestBody.caseId) &&
        Objects.equals(this.emailIds, barCodeShareRequestBody.emailIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseId, emailIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarCodeShareRequestBody {\n");
    sb.append("    caseId: ").append(toIndentedString(caseId)).append("\n");
    sb.append("    emailIds: ").append(toIndentedString(emailIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

