/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CaseDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MCASignatoryRequest
 */
@JsonPropertyOrder({
  MCASignatoryRequest.JSON_PROPERTY_CONSENT,
  MCASignatoryRequest.JSON_PROPERTY_CIN,
  MCASignatoryRequest.JSON_PROPERTY_IEC,
  MCASignatoryRequest.JSON_PROPERTY_COMPANY_NAME,
  MCASignatoryRequest.JSON_PROPERTY_CLIENT_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class MCASignatoryRequest {
  public static final String JSON_PROPERTY_CONSENT = "consent";
  private String consent;

  public static final String JSON_PROPERTY_CIN = "cin";
  private String cin;

  public static final String JSON_PROPERTY_IEC = "iec";
  private String iec;

  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  private String companyName;

  public static final String JSON_PROPERTY_CLIENT_DATA = "clientData";
  private CaseDetails clientData;

  public MCASignatoryRequest() {
  }

  public MCASignatoryRequest consent(String consent) {
    
    this.consent = consent;
    return this;
  }

   /**
   * Get consent
   * @return consent
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONSENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConsent() {
    return consent;
  }


  @JsonProperty(JSON_PROPERTY_CONSENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsent(String consent) {
    this.consent = consent;
  }


  public MCASignatoryRequest cin(String cin) {
    
    this.cin = cin;
    return this;
  }

   /**
   * Get cin
   * @return cin
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCin() {
    return cin;
  }


  @JsonProperty(JSON_PROPERTY_CIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCin(String cin) {
    this.cin = cin;
  }


  public MCASignatoryRequest iec(String iec) {
    
    this.iec = iec;
    return this;
  }

   /**
   * Get iec
   * @return iec
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IEC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIec() {
    return iec;
  }


  @JsonProperty(JSON_PROPERTY_IEC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIec(String iec) {
    this.iec = iec;
  }


  public MCASignatoryRequest companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public MCASignatoryRequest clientData(CaseDetails clientData) {
    
    this.clientData = clientData;
    return this;
  }

   /**
   * Get clientData
   * @return clientData
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CaseDetails getClientData() {
    return clientData;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientData(CaseDetails clientData) {
    this.clientData = clientData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MCASignatoryRequest mcASignatoryRequest = (MCASignatoryRequest) o;
    return Objects.equals(this.consent, mcASignatoryRequest.consent) &&
        Objects.equals(this.cin, mcASignatoryRequest.cin) &&
        Objects.equals(this.iec, mcASignatoryRequest.iec) &&
        Objects.equals(this.companyName, mcASignatoryRequest.companyName) &&
        Objects.equals(this.clientData, mcASignatoryRequest.clientData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consent, cin, iec, companyName, clientData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MCASignatoryRequest {\n");
    sb.append("    consent: ").append(toIndentedString(consent)).append("\n");
    sb.append("    cin: ").append(toIndentedString(cin)).append("\n");
    sb.append("    iec: ").append(toIndentedString(iec)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    clientData: ").append(toIndentedString(clientData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

