/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NewCaseRequestBody
 */
@JsonPropertyOrder({
  NewCaseRequestBody.JSON_PROPERTY_CASE_ID,
  NewCaseRequestBody.JSON_PROPERTY_CASE_NAME,
  NewCaseRequestBody.JSON_PROPERTY_CASE_DESCRIPTION,
  NewCaseRequestBody.JSON_PROPERTY_COMPANY_TYPE,
  NewCaseRequestBody.JSON_PROPERTY_BARCODE,
  NewCaseRequestBody.JSON_PROPERTY_BAR_CODE_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class NewCaseRequestBody {
  public static final String JSON_PROPERTY_CASE_ID = "caseId";
  private String caseId;

  public static final String JSON_PROPERTY_CASE_NAME = "caseName";
  private String caseName;

  public static final String JSON_PROPERTY_CASE_DESCRIPTION = "caseDescription";
  private String caseDescription;

  public static final String JSON_PROPERTY_COMPANY_TYPE = "companyType";
  private String companyType;

  public static final String JSON_PROPERTY_BARCODE = "barcode";
  private String barcode;

  /**
   * Gets or Sets barCodeStatus
   */
  public enum BarCodeStatusEnum {
    TRUE("TRUE"),
    
    FALSE("FALSE"),
    
    BLOCKED("BLOCKED");

    private String value;

    BarCodeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BarCodeStatusEnum fromValue(String value) {
      for (BarCodeStatusEnum b : BarCodeStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BAR_CODE_STATUS = "barCodeStatus";
  private BarCodeStatusEnum barCodeStatus;

  public NewCaseRequestBody() {
  }

  public NewCaseRequestBody caseId(String caseId) {
    
    this.caseId = caseId;
    return this;
  }

   /**
   * Get caseId
   * @return caseId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaseId() {
    return caseId;
  }


  @JsonProperty(JSON_PROPERTY_CASE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaseId(String caseId) {
    this.caseId = caseId;
  }


  public NewCaseRequestBody caseName(String caseName) {
    
    this.caseName = caseName;
    return this;
  }

   /**
   * Get caseName
   * @return caseName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CASE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCaseName() {
    return caseName;
  }


  @JsonProperty(JSON_PROPERTY_CASE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCaseName(String caseName) {
    this.caseName = caseName;
  }


  public NewCaseRequestBody caseDescription(String caseDescription) {
    
    this.caseDescription = caseDescription;
    return this;
  }

   /**
   * Get caseDescription
   * @return caseDescription
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CASE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCaseDescription() {
    return caseDescription;
  }


  @JsonProperty(JSON_PROPERTY_CASE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCaseDescription(String caseDescription) {
    this.caseDescription = caseDescription;
  }


  public NewCaseRequestBody companyType(String companyType) {
    
    this.companyType = companyType;
    return this;
  }

   /**
   * Get companyType
   * @return companyType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMPANY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCompanyType() {
    return companyType;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompanyType(String companyType) {
    this.companyType = companyType;
  }


  public NewCaseRequestBody barcode(String barcode) {
    
    this.barcode = barcode;
    return this;
  }

   /**
   * Get barcode
   * @return barcode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBarcode() {
    return barcode;
  }


  @JsonProperty(JSON_PROPERTY_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }


  public NewCaseRequestBody barCodeStatus(BarCodeStatusEnum barCodeStatus) {
    
    this.barCodeStatus = barCodeStatus;
    return this;
  }

   /**
   * Get barCodeStatus
   * @return barCodeStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BAR_CODE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BarCodeStatusEnum getBarCodeStatus() {
    return barCodeStatus;
  }


  @JsonProperty(JSON_PROPERTY_BAR_CODE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarCodeStatus(BarCodeStatusEnum barCodeStatus) {
    this.barCodeStatus = barCodeStatus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewCaseRequestBody newCaseRequestBody = (NewCaseRequestBody) o;
    return Objects.equals(this.caseId, newCaseRequestBody.caseId) &&
        Objects.equals(this.caseName, newCaseRequestBody.caseName) &&
        Objects.equals(this.caseDescription, newCaseRequestBody.caseDescription) &&
        Objects.equals(this.companyType, newCaseRequestBody.companyType) &&
        Objects.equals(this.barcode, newCaseRequestBody.barcode) &&
        Objects.equals(this.barCodeStatus, newCaseRequestBody.barCodeStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseId, caseName, caseDescription, companyType, barcode, barCodeStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewCaseRequestBody {\n");
    sb.append("    caseId: ").append(toIndentedString(caseId)).append("\n");
    sb.append("    caseName: ").append(toIndentedString(caseName)).append("\n");
    sb.append("    caseDescription: ").append(toIndentedString(caseDescription)).append("\n");
    sb.append("    companyType: ").append(toIndentedString(companyType)).append("\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    barCodeStatus: ").append(toIndentedString(barCodeStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

