/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NewCompanyRegistrationRequest
 */
@JsonPropertyOrder({
  NewCompanyRegistrationRequest.JSON_PROPERTY_COMPANY_NAME,
  NewCompanyRegistrationRequest.JSON_PROPERTY_AUTH_SIGN_EMAIL,
  NewCompanyRegistrationRequest.JSON_PROPERTY_AUTH_SIGN_MOBILE,
  NewCompanyRegistrationRequest.JSON_PROPERTY_PAN_NUMBER,
  NewCompanyRegistrationRequest.JSON_PROPERTY_GSTIN_NUMBER,
  NewCompanyRegistrationRequest.JSON_PROPERTY_COMPANY_TYPE,
  NewCompanyRegistrationRequest.JSON_PROPERTY_GSTINCTB,
  NewCompanyRegistrationRequest.JSON_PROPERTY_GSTIN_LEGAL_NAME,
  NewCompanyRegistrationRequest.JSON_PROPERTY_GSTIN_TRADE_NAME,
  NewCompanyRegistrationRequest.JSON_PROPERTY_ADDRESS,
  NewCompanyRegistrationRequest.JSON_PROPERTY_MEMEBER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class NewCompanyRegistrationRequest {
  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  private String companyName;

  public static final String JSON_PROPERTY_AUTH_SIGN_EMAIL = "authSignEmail";
  private String authSignEmail;

  public static final String JSON_PROPERTY_AUTH_SIGN_MOBILE = "authSignMobile";
  private Long authSignMobile;

  public static final String JSON_PROPERTY_PAN_NUMBER = "panNumber";
  private String panNumber;

  public static final String JSON_PROPERTY_GSTIN_NUMBER = "gstinNumber";
  private String gstinNumber;

  public static final String JSON_PROPERTY_COMPANY_TYPE = "companyType";
  private String companyType;

  public static final String JSON_PROPERTY_GSTINCTB = "gstinctb";
  private String gstinctb;

  public static final String JSON_PROPERTY_GSTIN_LEGAL_NAME = "gstinLegalName";
  private String gstinLegalName;

  public static final String JSON_PROPERTY_GSTIN_TRADE_NAME = "gstinTradeName";
  private String gstinTradeName;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_MEMEBER_ID = "memeberId";
  private Long memeberId;

  public NewCompanyRegistrationRequest() {
  }

  public NewCompanyRegistrationRequest companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public NewCompanyRegistrationRequest authSignEmail(String authSignEmail) {
    
    this.authSignEmail = authSignEmail;
    return this;
  }

   /**
   * Get authSignEmail
   * @return authSignEmail
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AUTH_SIGN_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuthSignEmail() {
    return authSignEmail;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_SIGN_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthSignEmail(String authSignEmail) {
    this.authSignEmail = authSignEmail;
  }


  public NewCompanyRegistrationRequest authSignMobile(Long authSignMobile) {
    
    this.authSignMobile = authSignMobile;
    return this;
  }

   /**
   * Get authSignMobile
   * @return authSignMobile
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTH_SIGN_MOBILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAuthSignMobile() {
    return authSignMobile;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_SIGN_MOBILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthSignMobile(Long authSignMobile) {
    this.authSignMobile = authSignMobile;
  }


  public NewCompanyRegistrationRequest panNumber(String panNumber) {
    
    this.panNumber = panNumber;
    return this;
  }

   /**
   * Get panNumber
   * @return panNumber
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPanNumber() {
    return panNumber;
  }


  @JsonProperty(JSON_PROPERTY_PAN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPanNumber(String panNumber) {
    this.panNumber = panNumber;
  }


  public NewCompanyRegistrationRequest gstinNumber(String gstinNumber) {
    
    this.gstinNumber = gstinNumber;
    return this;
  }

   /**
   * Get gstinNumber
   * @return gstinNumber
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GSTIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGstinNumber() {
    return gstinNumber;
  }


  @JsonProperty(JSON_PROPERTY_GSTIN_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGstinNumber(String gstinNumber) {
    this.gstinNumber = gstinNumber;
  }


  public NewCompanyRegistrationRequest companyType(String companyType) {
    
    this.companyType = companyType;
    return this;
  }

   /**
   * Get companyType
   * @return companyType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMPANY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCompanyType() {
    return companyType;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompanyType(String companyType) {
    this.companyType = companyType;
  }


  public NewCompanyRegistrationRequest gstinctb(String gstinctb) {
    
    this.gstinctb = gstinctb;
    return this;
  }

   /**
   * Get gstinctb
   * @return gstinctb
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GSTINCTB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGstinctb() {
    return gstinctb;
  }


  @JsonProperty(JSON_PROPERTY_GSTINCTB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGstinctb(String gstinctb) {
    this.gstinctb = gstinctb;
  }


  public NewCompanyRegistrationRequest gstinLegalName(String gstinLegalName) {
    
    this.gstinLegalName = gstinLegalName;
    return this;
  }

   /**
   * Get gstinLegalName
   * @return gstinLegalName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GSTIN_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGstinLegalName() {
    return gstinLegalName;
  }


  @JsonProperty(JSON_PROPERTY_GSTIN_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGstinLegalName(String gstinLegalName) {
    this.gstinLegalName = gstinLegalName;
  }


  public NewCompanyRegistrationRequest gstinTradeName(String gstinTradeName) {
    
    this.gstinTradeName = gstinTradeName;
    return this;
  }

   /**
   * Get gstinTradeName
   * @return gstinTradeName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GSTIN_TRADE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGstinTradeName() {
    return gstinTradeName;
  }


  @JsonProperty(JSON_PROPERTY_GSTIN_TRADE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGstinTradeName(String gstinTradeName) {
    this.gstinTradeName = gstinTradeName;
  }


  public NewCompanyRegistrationRequest address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(String address) {
    this.address = address;
  }


  public NewCompanyRegistrationRequest memeberId(Long memeberId) {
    
    this.memeberId = memeberId;
    return this;
  }

   /**
   * Get memeberId
   * @return memeberId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEMEBER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMemeberId() {
    return memeberId;
  }


  @JsonProperty(JSON_PROPERTY_MEMEBER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemeberId(Long memeberId) {
    this.memeberId = memeberId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewCompanyRegistrationRequest newCompanyRegistrationRequest = (NewCompanyRegistrationRequest) o;
    return Objects.equals(this.companyName, newCompanyRegistrationRequest.companyName) &&
        Objects.equals(this.authSignEmail, newCompanyRegistrationRequest.authSignEmail) &&
        Objects.equals(this.authSignMobile, newCompanyRegistrationRequest.authSignMobile) &&
        Objects.equals(this.panNumber, newCompanyRegistrationRequest.panNumber) &&
        Objects.equals(this.gstinNumber, newCompanyRegistrationRequest.gstinNumber) &&
        Objects.equals(this.companyType, newCompanyRegistrationRequest.companyType) &&
        Objects.equals(this.gstinctb, newCompanyRegistrationRequest.gstinctb) &&
        Objects.equals(this.gstinLegalName, newCompanyRegistrationRequest.gstinLegalName) &&
        Objects.equals(this.gstinTradeName, newCompanyRegistrationRequest.gstinTradeName) &&
        Objects.equals(this.address, newCompanyRegistrationRequest.address) &&
        Objects.equals(this.memeberId, newCompanyRegistrationRequest.memeberId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, authSignEmail, authSignMobile, panNumber, gstinNumber, companyType, gstinctb, gstinLegalName, gstinTradeName, address, memeberId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewCompanyRegistrationRequest {\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    authSignEmail: ").append(toIndentedString(authSignEmail)).append("\n");
    sb.append("    authSignMobile: ").append(toIndentedString(authSignMobile)).append("\n");
    sb.append("    panNumber: ").append(toIndentedString(panNumber)).append("\n");
    sb.append("    gstinNumber: ").append(toIndentedString(gstinNumber)).append("\n");
    sb.append("    companyType: ").append(toIndentedString(companyType)).append("\n");
    sb.append("    gstinctb: ").append(toIndentedString(gstinctb)).append("\n");
    sb.append("    gstinLegalName: ").append(toIndentedString(gstinLegalName)).append("\n");
    sb.append("    gstinTradeName: ").append(toIndentedString(gstinTradeName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    memeberId: ").append(toIndentedString(memeberId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

