/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CaseDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NSDLElectricityBillRequest
 */
@JsonPropertyOrder({
  NSDLElectricityBillRequest.JSON_PROPERTY_CONSENT,
  NSDLElectricityBillRequest.JSON_PROPERTY_CONSUMER_ID,
  NSDLElectricityBillRequest.JSON_PROPERTY_SERVICE_PROVIDER,
  NSDLElectricityBillRequest.JSON_PROPERTY_REG_MOBILE_NO,
  NSDLElectricityBillRequest.JSON_PROPERTY_CLIENT_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class NSDLElectricityBillRequest {
  public static final String JSON_PROPERTY_CONSENT = "consent";
  private String consent;

  public static final String JSON_PROPERTY_CONSUMER_ID = "consumer_id";
  private String consumerId;

  public static final String JSON_PROPERTY_SERVICE_PROVIDER = "service_provider";
  private String serviceProvider;

  public static final String JSON_PROPERTY_REG_MOBILE_NO = "regMobileNo";
  private String regMobileNo;

  public static final String JSON_PROPERTY_CLIENT_DATA = "clientData";
  private CaseDetails clientData;

  public NSDLElectricityBillRequest() {
  }

  public NSDLElectricityBillRequest consent(String consent) {
    
    this.consent = consent;
    return this;
  }

   /**
   * Get consent
   * @return consent
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONSENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConsent() {
    return consent;
  }


  @JsonProperty(JSON_PROPERTY_CONSENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsent(String consent) {
    this.consent = consent;
  }


  public NSDLElectricityBillRequest consumerId(String consumerId) {
    
    this.consumerId = consumerId;
    return this;
  }

   /**
   * Get consumerId
   * @return consumerId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONSUMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsumerId() {
    return consumerId;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsumerId(String consumerId) {
    this.consumerId = consumerId;
  }


  public NSDLElectricityBillRequest serviceProvider(String serviceProvider) {
    
    this.serviceProvider = serviceProvider;
    return this;
  }

   /**
   * Get serviceProvider
   * @return serviceProvider
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceProvider() {
    return serviceProvider;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceProvider(String serviceProvider) {
    this.serviceProvider = serviceProvider;
  }


  public NSDLElectricityBillRequest regMobileNo(String regMobileNo) {
    
    this.regMobileNo = regMobileNo;
    return this;
  }

   /**
   * Get regMobileNo
   * @return regMobileNo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REG_MOBILE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegMobileNo() {
    return regMobileNo;
  }


  @JsonProperty(JSON_PROPERTY_REG_MOBILE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegMobileNo(String regMobileNo) {
    this.regMobileNo = regMobileNo;
  }


  public NSDLElectricityBillRequest clientData(CaseDetails clientData) {
    
    this.clientData = clientData;
    return this;
  }

   /**
   * Get clientData
   * @return clientData
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CaseDetails getClientData() {
    return clientData;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientData(CaseDetails clientData) {
    this.clientData = clientData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NSDLElectricityBillRequest nsDLElectricityBillRequest = (NSDLElectricityBillRequest) o;
    return Objects.equals(this.consent, nsDLElectricityBillRequest.consent) &&
        Objects.equals(this.consumerId, nsDLElectricityBillRequest.consumerId) &&
        Objects.equals(this.serviceProvider, nsDLElectricityBillRequest.serviceProvider) &&
        Objects.equals(this.regMobileNo, nsDLElectricityBillRequest.regMobileNo) &&
        Objects.equals(this.clientData, nsDLElectricityBillRequest.clientData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consent, consumerId, serviceProvider, regMobileNo, clientData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NSDLElectricityBillRequest {\n");
    sb.append("    consent: ").append(toIndentedString(consent)).append("\n");
    sb.append("    consumerId: ").append(toIndentedString(consumerId)).append("\n");
    sb.append("    serviceProvider: ").append(toIndentedString(serviceProvider)).append("\n");
    sb.append("    regMobileNo: ").append(toIndentedString(regMobileNo)).append("\n");
    sb.append("    clientData: ").append(toIndentedString(clientData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

