/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubmitOTP
 */
@JsonPropertyOrder({
  SubmitOTP.JSON_PROPERTY_OTP,
  SubmitOTP.JSON_PROPERTY_TRANSACTION_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-02T01:38:15.284014500+05:30[Asia/Calcutta]")
public class SubmitOTP {
  public static final String JSON_PROPERTY_OTP = "otp";
  private String otp;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  private String transactionId;

  public SubmitOTP() {
  }

  public SubmitOTP otp(String otp) {
    
    this.otp = otp;
    return this;
  }

   /**
   * Get otp
   * @return otp
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOtp() {
    return otp;
  }


  @JsonProperty(JSON_PROPERTY_OTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtp(String otp) {
    this.otp = otp;
  }


  public SubmitOTP transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitOTP submitOTP = (SubmitOTP) o;
    return Objects.equals(this.otp, submitOTP.otp) &&
        Objects.equals(this.transactionId, submitOTP.transactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(otp, transactionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitOTP {\n");
    sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

