/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.SubmitOTP;
import org.openapitools.client.model.UidiaRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AadharManagementApi
 */
@Ignore
public class AadharManagementApiTest {

    private final AadharManagementApi api = new AadharManagementApi();

    
    /**
     * Delete aadhar details
     *
     * Delete aadhar OTP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAadharTest() {
        String caseId = null;
        Long aadharNumber = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.deleteAadhar(caseId, aadharNumber, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get aadhar details
     *
     * Submit aadhar OTP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAadharTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllAadhar(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Send aadhar OTP
     *
     * Send aadhar OTP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendOTPAadharTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        UidiaRequestBody uidiaRequestBody = null;
        ModelAPIResponse response = api.sendOTPAadhar(caseId, X_AUTH_TOKEN, uidiaRequestBody);

        // TODO: test validations
    }
    
    /**
     * Submit aadhar OTP
     *
     * Submit aadhar OTP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitOTPTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        SubmitOTP submitOTP = null;
        ModelAPIResponse response = api.submitOTP(caseId, X_AUTH_TOKEN, submitOTP);

        // TODO: test validations
    }
    
}
