/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BlockRequestBody;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminCompanyManagementApi
 */
@Ignore
public class AdminCompanyManagementApiTest {

    private final AdminCompanyManagementApi api = new AdminCompanyManagementApi();

    
    /**
     * Approve reject company registration
     *
     * Approve reject company registration
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void approveRejectCompany2Test() {
        String companyId = null;
        String status = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.approveRejectCompany2(companyId, status, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Block Unblock company user
     *
     * Block Unblock company user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void blockUnblocUserTest() {
        BlockRequestBody data = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.blockUnblocUser(data, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get all company
     *
     * Get all company
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCompanyTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllCompany(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get all registration for approval
     *
     * Get all registration for approval
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCompanyForApprovalTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllCompanyForApproval(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get all approved or rejected registration applications
     *
     * Get all approved or rejected registration applications
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCompanyForApproval1Test() {
        String X_AUTH_TOKEN = null;
        String status = null;
        ModelAPIResponse response = api.getAllCompanyForApproval1(X_AUTH_TOKEN, status);

        // TODO: test validations
    }
    
    /**
     * Get all registration whose email is not verified
     *
     * Get all registration whose email is not verified
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCompanyNoEmailApprovedTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllCompanyNoEmailApproved(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get company by code
     *
     * Get company by code
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyCodeTest() {
        String companyCode = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getCompanyCode(companyCode, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get company by code
     *
     * Get company by code
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyCodeDetailsFilterTest() {
        String key = null;
        String value = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getCompanyCodeDetailsFilter(key, value, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
