/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BankAccountVerification;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BankDetailsManagementApi
 */
@Ignore
public class BankDetailsManagementApiTest {

    private final BankDetailsManagementApi api = new BankDetailsManagementApi();

    
    /**
     * Add and verify new bank details
     *
     * Add and verify new bank details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addNewAndVerifyTest() {
        String X_AUTH_TOKEN = null;
        BankAccountVerification bankAccountVerification = null;
        ModelAPIResponse response = api.addNewAndVerify(X_AUTH_TOKEN, bankAccountVerification);

        // TODO: test validations
    }
    
    /**
     * Delete bank details
     *
     * Delete bank Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBankTest() {
        String X_AUTH_TOKEN = null;
        BankAccountVerification bankAccountVerification = null;
        ModelAPIResponse response = api.deleteBank(X_AUTH_TOKEN, bankAccountVerification);

        // TODO: test validations
    }
    
    /**
     * Get all bank details
     *
     * Get all bank details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllBankTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllBank(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
