/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.NewCaseRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaseManagementApi
 */
@Ignore
public class CaseManagementApiTest {

    private final CaseManagementApi api = new CaseManagementApi();

    
    /**
     * Create new case
     *
     * Create new case
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNewCaseTest() {
        String X_AUTH_TOKEN = null;
        NewCaseRequestBody newCaseRequestBody = null;
        ModelAPIResponse response = api.createNewCase(X_AUTH_TOKEN, newCaseRequestBody);

        // TODO: test validations
    }
    
    /**
     * Get all case fro company
     *
     * Get all case fro company
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCaseTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllCase(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get all case fro company
     *
     * Get all case fro company
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCaseAdminTest() {
        String companyId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllCaseAdmin(companyId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
