/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.MCACompanyMasterDataRequest;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyMasterDetailsManagementApi
 */
@Ignore
public class CompanyMasterDetailsManagementApiTest {

    private final CompanyMasterDetailsManagementApi api = new CompanyMasterDetailsManagementApi();

    
    /**
     * Get company master details from DB
     *
     * Get company master details from DB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyMasterDetailsTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getCompanyMasterDetails(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Update Company Master Details
     *
     * Update Company Master Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCompanyMasterDetails1Test() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        MCACompanyMasterDataRequest mcACompanyMasterDataRequest = null;
        ModelAPIResponse response = api.updateCompanyMasterDetails1(caseId, X_AUTH_TOKEN, mcACompanyMasterDataRequest);

        // TODO: test validations
    }
    
}
