/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.NSDLElectricityBillRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ElectricityBillDetailsManagementApi
 */
@Ignore
public class ElectricityBillDetailsManagementApiTest {

    private final ElectricityBillDetailsManagementApi api = new ElectricityBillDetailsManagementApi();

    
    /**
     * Get electricity bill details from DB
     *
     * Get electricity bill details from DB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateElectricityBillFromDBTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.updateElectricityBillFromDB(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Update electricity bill Details
     *
     * Update electricity bill Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateElectricityBillFromNSDLTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        NSDLElectricityBillRequest nsDLElectricityBillRequest = null;
        ModelAPIResponse response = api.updateElectricityBillFromNSDL(caseId, X_AUTH_TOKEN, nsDLElectricityBillRequest);

        // TODO: test validations
    }
    
}
