/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.io.File;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExcelManagementApi
 */
@Ignore
public class ExcelManagementApiTest {

    private final ExcelManagementApi api = new ExcelManagementApi();

    
    /**
     * Get All Upload Id
     *
     * Get All Upload Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUploadIdTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllUploadId(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get All Record inside Upload Id
     *
     * Get All Record inside Upload Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUploadIdRecordsTest() {
        String uploadId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllUploadIdRecords(uploadId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Upload Excel
     *
     * Upload Excel
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadExcelFileTest() {
        String X_AUTH_TOKEN = null;
        File _file = null;
        ModelAPIResponse response = api.uploadExcelFile(X_AUTH_TOKEN, _file);

        // TODO: test validations
    }
    
}
