/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.GstinRequest;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GstinManagementApi
 */
@Ignore
public class GstinManagementApiTest {

    private final GstinManagementApi api = new GstinManagementApi();

    
    /**
     * Delete GSTIN details
     *
     * Delete GSTIN details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGSTINTest() {
        String X_AUTH_TOKEN = null;
        GstinRequest gstinRequest = null;
        ModelAPIResponse response = api.deleteGSTIN(X_AUTH_TOKEN, gstinRequest);

        // TODO: test validations
    }
    
    /**
     * Get all GSTIN
     *
     * Get all GSTIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetailsGSTINTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getDetailsGSTIN(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Add new GSTIN
     *
     * Add new GSTIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetailsGSTIN1Test() {
        String X_AUTH_TOKEN = null;
        GstinRequest gstinRequest = null;
        ModelAPIResponse response = api.getDetailsGSTIN1(X_AUTH_TOKEN, gstinRequest);

        // TODO: test validations
    }
    
    /**
     * Update GSTIN current status from GSP
     *
     * Update GSTIN current status from GSP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGSTINStatusTest() {
        String X_AUTH_TOKEN = null;
        GstinRequest gstinRequest = null;
        ModelAPIResponse response = api.getGSTINStatus(X_AUTH_TOKEN, gstinRequest);

        // TODO: test validations
    }
    
    /**
     * Update GSTIN preference details GSP
     *
     * Update GSTIN preference details GSP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPreferenceDetailsGSTINTest() {
        String fy = null;
        String X_AUTH_TOKEN = null;
        GstinRequest gstinRequest = null;
        ModelAPIResponse response = api.getPreferenceDetailsGSTIN(fy, X_AUTH_TOKEN, gstinRequest);

        // TODO: test validations
    }
    
    /**
     * Update GSTIN return track status details GSP
     *
     * Update GSTIN return track status details GSP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTrackDetailsGSTINTest() {
        String fy = null;
        String type = null;
        String X_AUTH_TOKEN = null;
        GstinRequest gstinRequest = null;
        ModelAPIResponse response = api.getTrackDetailsGSTIN(fy, type, X_AUTH_TOKEN, gstinRequest);

        // TODO: test validations
    }
    
}
