/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GstinUtilityManagementApi
 */
@Ignore
public class GstinUtilityManagementApiTest {

    private final GstinUtilityManagementApi api = new GstinUtilityManagementApi();

    
    /**
     * Get all finacial years
     *
     * Get all finacial years
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllFyTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllFy(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get all return types
     *
     * Get all return types
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllReturnTypeTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllReturnType(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get GSTIN status from DB
     *
     * Get GSTIN status from DB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGSTINStatus1Test() {
        String gstin = null;
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getGSTINStatus1(gstin, caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get GSTIN preference from DB
     *
     * Get GSTIN preference from DB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPreferenceDetailsGSTIN1Test() {
        String gstin = null;
        String fy = null;
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getPreferenceDetailsGSTIN1(gstin, fy, caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get GSTIN track details from DB
     *
     * Get GSTIN track details from DB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTrackDetailsGSTIN1Test() {
        String gstin = null;
        String fy = null;
        String type = null;
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getTrackDetailsGSTIN1(gstin, fy, type, caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
