/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.MCASignatoryRequest;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IecDetailsManagementApi
 */
@Ignore
public class IecDetailsManagementApiTest {

    private final IecDetailsManagementApi api = new IecDetailsManagementApi();

    
    /**
     * Get IEC details from DB
     *
     * Get IEC details from DB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIECDetailsTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getIECDetails(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Update IEC details from NSDL
     *
     * Update IEC details from NSDL
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateIECDetails1Test() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        MCASignatoryRequest mcASignatoryRequest = null;
        ModelAPIResponse response = api.updateIECDetails1(caseId, X_AUTH_TOKEN, mcASignatoryRequest);

        // TODO: test validations
    }
    
}
