/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.NSDLRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NsdlEncDcManagementApi
 */
@Ignore
public class NsdlEncDcManagementApiTest {

    private final NsdlEncDcManagementApi api = new NsdlEncDcManagementApi();

    
    /**
     * Decrypt NSDL response body
     *
     * Decrypt NSDL response body
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void decryptDataTest() {
        String X_AUTH_TOKEN = null;
        NSDLRequestBody nsDLRequestBody = null;
        ModelAPIResponse response = api.decryptData(X_AUTH_TOKEN, nsDLRequestBody);

        // TODO: test validations
    }
    
    /**
     * Encrypt NSDL request body
     *
     * Encrypt NSDL request body
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void encryptDataTest() {
        String X_AUTH_TOKEN = null;
        String body = null;
        ModelAPIResponse response = api.encryptData(X_AUTH_TOKEN, body);

        // TODO: test validations
    }
    
}
