/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.PanRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PanManagementApi
 */
@Ignore
public class PanManagementApiTest {

    private final PanManagementApi api = new PanManagementApi();

    
    /**
     * Fetch PAN details from NSDL
     *
     * Fetch PAN details from NSDL
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetailsFromPanNumberTest() {
        String X_AUTH_TOKEN = null;
        PanRequestBody panRequestBody = null;
        ModelAPIResponse response = api.getDetailsFromPanNumber(X_AUTH_TOKEN, panRequestBody);

        // TODO: test validations
    }
    
    /**
     * Fetch PAN details from DB Case ID
     *
     * Fetch PAN details from DB Case ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetailsFromPanNumberFromCAseTest() {
        String caseId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getDetailsFromPanNumberFromCAse(caseId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
