/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentDetailsManagementApi
 */
@Ignore
public class PaymentDetailsManagementApiTest {

    private final PaymentDetailsManagementApi api = new PaymentDetailsManagementApi();

    
    /**
     * Create payment link
     *
     * Create Payment links
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentDetailsTest() {
        String paymentId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getPaymentDetails(paymentId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * All Payments
     *
     * Get All payments
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentDetails1Test() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getPaymentDetails1(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Create payment link
     *
     * Create Payment links
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateIECDetailsTest() {
        Double amount = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.updateIECDetails(amount, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
