/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.PasswordChangeRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileManagementApi
 */
@Ignore
public class ProfileManagementApiTest {

    private final ProfileManagementApi api = new ProfileManagementApi();

    
    /**
     * Get Balance
     *
     * Get Balance
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBalanceTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getBalance(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get Company Profile
     *
     * Get Company Profile
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProfileTest() {
        String companyId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getProfile(companyId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Send Password change OTP email
     *
     * Send Password change OTP email
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendOTPForPasswordChangeTest() {
        String companyId = null;
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.sendOTPForPasswordChange(companyId, X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Update Password
     *
     * Update Password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendPasswordResetLinkTest() {
        String data = null;
        ModelAPIResponse response = api.sendPasswordResetLink(data);

        // TODO: test validations
    }
    
    /**
     * Update Password
     *
     * Update Password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePasswordTest() {
        String X_AUTH_TOKEN = null;
        PasswordChangeRequest passwordChangeRequest = null;
        ModelAPIResponse response = api.updatePassword(X_AUTH_TOKEN, passwordChangeRequest);

        // TODO: test validations
    }
    
}
