/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.RateRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RateMasterDetailsManagementApi
 */
@Ignore
public class RateMasterDetailsManagementApiTest {

    private final RateMasterDetailsManagementApi api = new RateMasterDetailsManagementApi();

    
    /**
     * Create new rate
     *
     * Create new rate
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNewRateTest() {
        String X_AUTH_TOKEN = null;
        RateRequest rateRequest = null;
        ModelAPIResponse response = api.createNewRate(X_AUTH_TOKEN, rateRequest);

        // TODO: test validations
    }
    
    /**
     * Get all rates
     *
     * Get all rates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllRatesTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllRates(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
    /**
     * Get all Services
     *
     * Get all services
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllServicesTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.getAllServices(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
