/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.openapitools.client.model.NewCompanyRegistrationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegistrationManagementApi
 */
@Ignore
public class RegistrationManagementApiTest {

    private final RegistrationManagementApi api = new RegistrationManagementApi();

    
    /**
     * Get GSTIN details from GSP
     *
     * Get GSTIN status from GSP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGSTINDetailsUtilityForVerifyTest() {
        String gstin = null;
        String X_CLIENT_ID = null;
        String X_CLIENT_SECRET = null;
        ModelAPIResponse response = api.getGSTINDetailsUtilityForVerify(gstin, X_CLIENT_ID, X_CLIENT_SECRET);

        // TODO: test validations
    }
    
    /**
     * create new case
     *
     * create new case
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newRegistrationTest() {
        NewCompanyRegistrationRequest newCompanyRegistrationRequest = null;
        ModelAPIResponse response = api.newRegistration(newCompanyRegistrationRequest);

        // TODO: test validations
    }
    
    /**
     * Fetch PAN details from NSDL
     *
     * Fetch PAN details from NSDL
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyPANumberForVerifyTest() {
        String pan = null;
        String X_CLIENT_ID = null;
        String X_CLIENT_SECRET = null;
        ModelAPIResponse response = api.verifyPANumberForVerify(pan, X_CLIENT_ID, X_CLIENT_SECRET);

        // TODO: test validations
    }
    
}
