/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.LoginRequestBody;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SessionManagementApi
 */
@Ignore
public class SessionManagementApiTest {

    private final SessionManagementApi api = new SessionManagementApi();

    
    /**
     * Login
     *
     * Login
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void approveRejectCompanyTest() {
        LoginRequestBody loginRequestBody = null;
        ModelAPIResponse response = api.approveRejectCompany(loginRequestBody);

        // TODO: test validations
    }
    
    /**
     * Get all case
     *
     * Get all case
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void approveRejectCompany1Test() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.approveRejectCompany1(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
