/*
 * e-KYC API
 * e-KYC API , GST verification suite
 *
 * The version of the OpenAPI document: v1
 * Contact: gautam@balajimariline.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaskManagementApi
 */
@Ignore
public class TaskManagementApiTest {

    private final TaskManagementApi api = new TaskManagementApi();

    
    /**
     * Execute Task
     *
     * Execute Task
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeTaskTest() {
        String X_AUTH_TOKEN = null;
        ModelAPIResponse response = api.executeTask(X_AUTH_TOKEN);

        // TODO: test validations
    }
    
}
